### ISSUE TITLE
Create AUR package and publish it

### ISSUE THREAD

**Issue by ryukinix** [ryukinix/mal#19]
We just provide a PKGBUILD linked with the releases of github. A template system for python packages can be found here: https://wiki.archlinux.org/index.php/Python_package_guidelines

However, we need put [`decorating`](https://github.com/ryukinix/decorating/issues/19) on AUR before, because all the packages need be tracked for pacman to do this in the right way

**Comment by alexkubica** [comment]
They're both on aur already!
See [python-decorating](https://aur.archlinux.org/packages/python-decorating/) and [python-mal-git](https://aur.archlinux.org/packages/python-mal-git), they're both maintained by me :)
After you release a new version all we need to do is update the pkgver variables, and maybe depends if dependencies were added.

**Comment by ryukinix** [comment]
Thanks!!!! I'll test.

**Comment by ryukinix** [comment]
![screenshot_2016-10-26_16-25-17](https://cloud.githubusercontent.com/assets/7642878/19741883/e47c026c-9b98-11e6-8574-499839a06a29.png)

You can check later this for me?

**Comment by alexkubica** [comment]
When I uploaded to aur this commit still existed, have you deleted it maybe?
If so, the source variable should be updated.
Also, check that you don't have the installed files already so it won't conflict when installing the package, for example: `/bin/mal`

**Comment by ryukinix** [comment]
I didn't deleted anything, although something can be lost on some rebase. You need make sure to use only commits on master on tagged, the dev in general can be unstable. That commit is in which branch?

I didn't have mal installed yet.

**Comment by alexkubica** [comment]
I couldn't use master at that time because it's dependencies were outdated.
Git packages are usually not stable too so it's ok.

**Comment by ryukinix** [comment]
Well, we need just update readme to get a new release on master. But try later a quick fix for this, if you can.

**Comment by alexkubica** [comment]
Okay, after the new release I'll change the package to clone branch master instead but we should always make sure that master works good. I'll see what I can do about current package.
I will also work on the readme, I assume your'e talking about https://github.com/ryukinix/mal/issues/8.
You should also release a new version for decorating for the last PR :)

**Comment by alexkubica** [comment]
I have updated the package, try again:
https://aur.archlinux.org/packages/python-mal-git

**Comment by ryukinix** [comment]
Now I got. Installed with success. But I don't understand the necessity of `python-argparse`. Why we need that? This wouldn't already on stdlib?

**Comment by ryukinix** [comment]
> You should also release a new version for decorating for the last PR :)

Yes, I'll do.

**Comment by ryukinix** [comment]
We already have a new version of [decorating](https://github.com/ryukinix/decorating/releases/tag/v0.5.2)

**Comment by alexkubica** [comment]
That's great, I'll update the packages.
About `python-argparse` it was on AUR so I added it because **it is** a dependency.
I'll ask on the forums if it's needed even though it's on stdlib.

**Comment by alexkubica** [comment]
Posted the question [here](https://bbs.archlinux.org/viewtopic.php?pid=1665175).

**Comment by ryukinix** [comment]
[After Python 3.2](https://docs.python.org/3/library/argparse.html) version argparse was merged into stdlib. I think is desnecessary as mal is written based at least Python3.2.

But your package your rules. However, I expect this is not on requirements.txt file as well.

**Comment by alexkubica** [comment]
Ohh you meant requirements.txt! Well I'll remove it if it's not needed.

**Comment by ryukinix** [comment]
I update the manoel.tk/MAL usage too.

**Comment by ryukinix** [comment]
Okay. I think we can close that. Any useful information later (or problem) you have the right to re-opened this issue again.

**Comment by alexkubica** [comment]
Alright.
I updated decorating and mal on AUR.

**Comment by ryukinix** [comment]
Thanks. I'll update the master of mal in soon, as well publish the `v0.2` version on PyPI. Thanks for all the help!

**Comment by ryukinix** [comment]
Well, the new version of mal is on master. You can use directly the master on AUR? I have some troubles for now to use mal based on AUR package because he needs decorating v0.5 and AUR provides v0.5.2

**Comment by ryukinix** [comment]
I made a patch. I'll be glad if you merge it. Here the `format-patch`: http://sprunge.us/MSZi

I tested on my machine and are working fine for now.

**Comment by alexkubica** [comment]
Thanks I'll update.
I'll make you a maintainer on aur too.

**Comment by alexkubica** [comment]
I'm trying to package it but I get an error:

```
[alex@archlinux Downloads]$ makepkg -fi
==> Making package: python-mal-git r117.81ebdf1-1 (Sat Oct 29 14:18:49 IDT 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating mal git repo...
Fetching origin
==> Validating source files with md5sums...
    mal ... Skipped
==> Extracting sources...
  -> Creating working copy of mal git repo...
Reset branch 'makepkg'
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    long_description = pypandoc.convert(readme, 'rst', format='markdown')
  File "/usr/lib/python3.5/site-packages/pypandoc/__init__.py", line 69, in convert
    outputfile=outputfile, filters=filters)
  File "/usr/lib/python3.5/site-packages/pypandoc/__init__.py", line 240, in _convert_input
    format, to = _validate_formats(format, to, outputfile)
  File "/usr/lib/python3.5/site-packages/pypandoc/__init__.py", line 201, in _validate_formats
    from_formats, to_formats = get_pandoc_formats()
  File "/usr/lib/python3.5/site-packages/pypandoc/__init__.py", line 335, in get_pandoc_formats
    str(comm))
RuntimeError: Couldn't call pandoc to get output formats. Output from pandoc:
(b'pandoc [OPTIONS] [FILES]\n  -f FORMAT, -r FORMAT  --from=FORMAT, --read=FORMAT                    \n  -t FORMAT, -w FORMAT  --to=FORMAT, --write=FORMAT                     \n  -o FILENAME           --output=FILENAME                               \n                        --data-dir=DIRECTORY                            \n  -R                    --parse-raw                                     \n  -S                    --smart                                         \n                        --old-dashes                                    \n                        --base-header-level=NUMBER                      \n                        --indented-code-classes=STRING                  \n  -F PROGRAM            --filter=PROGRAM                                \n                        --normalize                                     \n  -p                    --preserve-tabs                                 \n                        --tab-stop=NUMBER                               \n                        --track-changes=accept|reject|all               \n                        --file-scope                                    \n                        --extract-media=PATH                            \n  -s                    --standalone                                    \n                        --template=FILENAME                             \n  -M KEY[:VALUE]        --metadata=KEY[:VALUE]                          \n  -V KEY[:VALUE]        --variable=KEY[:VALUE]                          \n  -D FORMAT             --print-default-template=FORMAT                 \n                        --print-default-data-file=FILE                  \n                        --dpi=NUMBER                                    \n                        --no-wrap                                       \n                        --wrap=[auto|none|preserve]                     \n                        --columns=NUMBER                                \n                        --toc, --table-of-contents                      \n                        --toc-depth=NUMBER                              \n                        --no-highlight                                  \n                        --highlight-style=STYLE                         \n  -H FILENAME           --include-in-header=FILENAME                    \n  -B FILENAME           --include-before-body=FILENAME                  \n  -A FILENAME           --include-after-body=FILENAME                   \n                        --self-contained                                \n                        --html-q-tags                                   \n                        --ascii                                         \n                        --reference-links                               \n                        --reference-location=block|section|document     \n                        --atx-headers                                   \n                        --chapters                                      \n                        --top-level-division=[section|chapter|part]     \n  -N                    --number-sections                               \n                        --number-offset=NUMBERS                         \n                        --no-tex-ligatures                              \n                        --listings                                      \n  -i                    --incremental                                   \n                        --slide-level=NUMBER                            \n                        --section-divs                                  \n                        --default-image-extension=extension             \n                        --email-obfuscation=none|javascript|references  \n                        --id-prefix=STRING                              \n  -T STRING             --title-prefix=STRING                           \n  -c URL                --css=URL                                       \n                        --reference-odt=FILENAME                        \n                        --reference-docx=FILENAME                       \n                        --epub-stylesheet=FILENAME                      \n                        --epub-cover-image=FILENAME                     \n                        --epub-metadata=FILENAME                        \n                        --epub-embed-font=FILE                          \n                        --epub-chapter-level=NUMBER                     \n                        --latex-engine=PROGRAM                          \n                        --latex-engine-opt=STRING                       \n                        --bibliography=FILE                             \n                        --csl=FILE                                      \n                        --citation-abbreviations=FILE                   \n                        --natbib                                        \n                        --biblatex                                      \n  -m[URL]               --latexmathml[=URL], --asciimathml[=URL]        \n                        --mathml[=URL]                                  \n                        --mimetex[=URL]                                 \n                        --webtex[=URL]                                  \n                        --jsmath[=URL]                                  \n                        --mathjax[=URL]                                 \n                        --katex[=URL]                                   \n                        --katex-stylesheet=URL                          \n                        --gladtex                                       \n                        --trace                                         \n                        --dump-args                                     \n                        --ignore-args                                   \n                        --verbose                                       \n                        --bash-completion                               \n                        --list-input-formats                            \n                        --list-output-formats                           \n                        --list-extensions                               \n                        --list-highlight-languages                      \n                        --list-highlight-styles                         \n  -v                    --version                                       \n  -h                    --help                                          \n', None)
==> ERROR: A failure occurred in package().
    Aborting...
```

Could you check it?

**Comment by ryukinix** [comment]
This is weird. It's like you have the python-bindings for pandoc (`pypandoc`) but don't have pandoc. You can import `pypandoc`?

![image](https://cloud.githubusercontent.com/assets/7642878/19831449/b70896ac-9de0-11e6-9023-a75f1bd23557.png)

**Comment by ryukinix** [comment]
Well, I think the package are ok, so I'll close for now. Any problem you can reopen this again.
