### ISSUE TITLE
Log in loop due to Attribute Error.

### ISSUE THREAD

**Issue by m311o** [ryukinix/mal#56]
When trying to use mal on python 3.6.1, I'm unable to log in due to an attribute error. Here is the exact error I get:

```
 ⣾ validating login ▁Traceback (most recent call last):
  File "/usr/bin/mal", line 11, in <module>
    load_entry_point('mal==0.3.0', 'console_scripts', 'mal')()
  File "/usr/lib/python3.6/site-packages/mal/cli.py", line 128, in main
    config = login.get_credentials()
  File "/usr/lib/python3.6/site-packages/mal/login.py", line 24, in get_credentials
    config = create_credentials()
  File "/usr/lib/python3.6/site-packages/mal/login.py", line 39, in create_credentials
    if MyAnimeList.validate_login(config[setup.LOGIN_SECTION]):
  File "/usr/lib/python3.6/site-packages/mal/utils.py", line 85, in wrapper
    result = func(*args, **kwargs)
  File "/home/m3llo/.local/lib/python3.6/site-packages/decorating/decorator.py", line 127, in _wrapper
    result = function(*args, **kargs)
  File "/usr/lib/python3.6/site-packages/mal/api.py", line 52, in validate_login
    self.base_url + '/account/verify_credentials.xml',
AttributeError: 'SectionProxy' object has no attribute 'base_url'
```

**Comment by mparadinha** [comment]
It should be fixed now in `master` branch.

**Comment by m311o** [comment]
Thank you! All is working great now.
